### PR TITLE
Delete User, delete post, change

### PR DESCRIPTION
**Pull request by PrototypeK02**
Delete and change roles

### CODE REVIEW

**Review by JhonatanPG02 — DISMISSED** [review]
Realizar cambios

**Review by Hecatonquir — APPROVED** [review]
Sin conflictos, parece todo ok

**Review by PrototypeK02 — COMMENTED** [review]
listo

**Review by Hecatonquir — APPROVED** [review]
ahora si?

**Review by PrototypeK02 — COMMENTED** [review]
done

**Review by Hecatonquir — APPROVED** [review]
y ahora?

**Pull request merged**
